import React from "react";
import { Link } from "react-router-dom";

const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">CoordinatorScreen</Link>
        </li>
        <li>
          <Link to="/leaderboard">Leaderboard</Link>
        </li>
        <li>
          <Link to="/homenotloggedin">HomeNotLoggedIn</Link>
        </li>
        <li>
          <Link to="/homeloggedin">HomeLoggedIn</Link>
        </li>
        <li>
          <Link to="/overlay">Overlay</Link>
        </li>
        <li>
          <Link to="/overlayone">OverlayOne</Link>
        </li>
        <li>
          <Link to="/overlaytwo">OverlayTwo</Link>
        </li>
        <li>
          <Link to="/overlaythree">OverlayThree</Link>
        </li>
      </ul>
    </div>
  );
};

export default Home;
